// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: auth.proto

package net.dracones.bankng;

public interface FirstFactorRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:net.dracones.bankng.FirstFactorRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string full_name = 1;</code>
   * @return The fullName.
   */
  java.lang.String getFullName();
  /**
   * <code>string full_name = 1;</code>
   * @return The bytes for fullName.
   */
  com.google.protobuf.ByteString
      getFullNameBytes();
}
