// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: accounts.proto

package bankng;

public interface AccountOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bankng.Account)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string iban = 1;</code>
   * @return The iban.
   */
  java.lang.String getIban();
  /**
   * <code>string iban = 1;</code>
   * @return The bytes for iban.
   */
  com.google.protobuf.ByteString
      getIbanBytes();

  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string currency = 3;</code>
   * @return The currency.
   */
  java.lang.String getCurrency();
  /**
   * <code>string currency = 3;</code>
   * @return The bytes for currency.
   */
  com.google.protobuf.ByteString
      getCurrencyBytes();

  /**
   * <code>string currency_code = 4;</code>
   * @return The currencyCode.
   */
  java.lang.String getCurrencyCode();
  /**
   * <code>string currency_code = 4;</code>
   * @return The bytes for currencyCode.
   */
  com.google.protobuf.ByteString
      getCurrencyCodeBytes();

  /**
   * <code>string balance = 5;</code>
   * @return The balance.
   */
  java.lang.String getBalance();
  /**
   * <code>string balance = 5;</code>
   * @return The bytes for balance.
   */
  com.google.protobuf.ByteString
      getBalanceBytes();
}
