// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: auth.proto

package bankng;

public final class AuthOuterClass {
  private AuthOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bankng_FirstFactorRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bankng_FirstFactorRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bankng_FirstFactorReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bankng_FirstFactorReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bankng_SecondFactorRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bankng_SecondFactorRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bankng_SecondFactorReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bankng_SecondFactorReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nauth.proto\022\006bankng\"\'\n\022FirstFactorReque" +
      "st\022\021\n\tfull_name\030\001 \001(\t\"^\n\020FirstFactorRepl" +
      "y\022\021\n\tfull_name\030\001 \001(\t\022\022\n\nfirst_name\030\002 \001(\t" +
      "\022\017\n\007pfp_url\030\003 \001(\t\022\022\n\nsession_id\030\004 \001(\t\"7\n" +
      "\023SecondFactorRequest\022\022\n\nsession_id\030\001 \001(\t" +
      "\022\014\n\004code\030\002 \001(\t\" \n\021SecondFactorReply\022\013\n\003j" +
      "wt\030\001 \001(\t2\227\001\n\004Auth\022E\n\013FirstFactor\022\032.bankn" +
      "g.FirstFactorRequest\032\030.bankng.FirstFacto" +
      "rReply\"\000\022H\n\014SecondFactor\022\033.bankng.Second" +
      "FactorRequest\032\031.bankng.SecondFactorReply" +
      "\"\000B\002P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_bankng_FirstFactorRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_bankng_FirstFactorRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bankng_FirstFactorRequest_descriptor,
        new java.lang.String[] { "FullName", });
    internal_static_bankng_FirstFactorReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_bankng_FirstFactorReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bankng_FirstFactorReply_descriptor,
        new java.lang.String[] { "FullName", "FirstName", "PfpUrl", "SessionId", });
    internal_static_bankng_SecondFactorRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_bankng_SecondFactorRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bankng_SecondFactorRequest_descriptor,
        new java.lang.String[] { "SessionId", "Code", });
    internal_static_bankng_SecondFactorReply_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_bankng_SecondFactorReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bankng_SecondFactorReply_descriptor,
        new java.lang.String[] { "Jwt", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
