// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bankng.proto

package bankng;

public final class Bankng {
  private Bankng() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
    registry.add(bankng.Bankng.requiresAuth);
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public static final int REQUIRES_AUTH_FIELD_NUMBER = 50001;
  /**
   * <code>extend .google.protobuf.MethodOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MethodOptions,
      java.lang.Boolean> requiresAuth = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Boolean.class,
        null);
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bankng_ListAccountsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bankng_ListAccountsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bankng_ListAccountsReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bankng_ListAccountsReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bankng_Account_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bankng_Account_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bankng_ListTransactionsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bankng_ListTransactionsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bankng_ListTransactionsReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bankng_ListTransactionsReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bankng_Transaction_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bankng_Transaction_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bankng_Correspondent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bankng_Correspondent_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bankng_CreateTransactionRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bankng_CreateTransactionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bankng_CreateTransactionReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bankng_CreateTransactionReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014bankng.proto\022\006bankng\032\037google/protobuf/" +
      "timestamp.proto\032 google/protobuf/descrip" +
      "tor.proto\"\025\n\023ListAccountsRequest\"6\n\021List" +
      "AccountsReply\022!\n\010accounts\030\001 \003(\0132\017.bankng" +
      ".Account\"_\n\007Account\022\014\n\004iban\030\001 \001(\t\022\014\n\004nam" +
      "e\030\002 \001(\t\022\020\n\010currency\030\003 \001(\t\022\025\n\rcurrency_co" +
      "de\030\004 \001(\t\022\017\n\007balance\030\005 \001(\t\"\'\n\027ListTransac" +
      "tionsRequest\022\014\n\004iban\030\001 \001(\t\"B\n\025ListTransa" +
      "ctionsReply\022)\n\014transactions\030\001 \003(\0132\023.bank" +
      "ng.Transaction\"z\n\013Transaction\022,\n\rcorresp" +
      "ondent\030\001 \001(\0132\025.bankng.Correspondent\022\016\n\006a" +
      "mount\030\002 \001(\t\022-\n\ttimestamp\030\005 \001(\0132\032.google." +
      "protobuf.Timestamp\".\n\rCorrespondent\022\014\n\004n" +
      "ame\030\001 \001(\t\022\017\n\007pfp_url\030\002 \001(\t\"{\n\030CreateTran" +
      "sactionRequest\022\021\n\tfrom_iban\030\001 \001(\t\022\016\n\004iba" +
      "n\030\002 \001(\tH\000\022\016\n\004name\030\003 \001(\tH\000\022\016\n\006amount\030\004 \001(" +
      "\t\022\026\n\016transaction_id\030\005 \001(\tB\004\n\002to\"B\n\026Creat" +
      "eTransactionReply\022(\n\013transaction\030\001 \001(\0132\023" +
      ".bankng.Transaction2\262\001\n\010Accounts\022L\n\014List" +
      "Accounts\022\033.bankng.ListAccountsRequest\032\031." +
      "bankng.ListAccountsReply\"\004\210\265\030\001\022X\n\020ListTr" +
      "ansactions\022\037.bankng.ListTransactionsRequ" +
      "est\032\035.bankng.ListTransactionsReply\"\004\210\265\030\001" +
      "2k\n\014Transactions\022[\n\021CreateTransaction\022 ." +
      "bankng.CreateTransactionRequest\032\036.bankng" +
      ".CreateTransactionReply\"\004\210\265\030\001:7\n\rrequire" +
      "s_auth\022\036.google.protobuf.MethodOptions\030\321" +
      "\206\003 \001(\010B\002P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
          com.google.protobuf.DescriptorProtos.getDescriptor(),
        });
    internal_static_bankng_ListAccountsRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_bankng_ListAccountsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bankng_ListAccountsRequest_descriptor,
        new java.lang.String[] { });
    internal_static_bankng_ListAccountsReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_bankng_ListAccountsReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bankng_ListAccountsReply_descriptor,
        new java.lang.String[] { "Accounts", });
    internal_static_bankng_Account_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_bankng_Account_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bankng_Account_descriptor,
        new java.lang.String[] { "Iban", "Name", "Currency", "CurrencyCode", "Balance", });
    internal_static_bankng_ListTransactionsRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_bankng_ListTransactionsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bankng_ListTransactionsRequest_descriptor,
        new java.lang.String[] { "Iban", });
    internal_static_bankng_ListTransactionsReply_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_bankng_ListTransactionsReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bankng_ListTransactionsReply_descriptor,
        new java.lang.String[] { "Transactions", });
    internal_static_bankng_Transaction_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_bankng_Transaction_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bankng_Transaction_descriptor,
        new java.lang.String[] { "Correspondent", "Amount", "Timestamp", });
    internal_static_bankng_Correspondent_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_bankng_Correspondent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bankng_Correspondent_descriptor,
        new java.lang.String[] { "Name", "PfpUrl", });
    internal_static_bankng_CreateTransactionRequest_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_bankng_CreateTransactionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bankng_CreateTransactionRequest_descriptor,
        new java.lang.String[] { "FromIban", "Iban", "Name", "Amount", "TransactionId", "To", });
    internal_static_bankng_CreateTransactionReply_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_bankng_CreateTransactionReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bankng_CreateTransactionReply_descriptor,
        new java.lang.String[] { "Transaction", });
    requiresAuth.internalInit(descriptor.getExtensions().get(0));
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(bankng.Bankng.requiresAuth);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.protobuf.TimestampProto.getDescriptor();
    com.google.protobuf.DescriptorProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
