// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bankng.proto

package bankng;

public interface CorrespondentOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bankng.Correspondent)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string pfp_url = 2;</code>
   * @return The pfpUrl.
   */
  java.lang.String getPfpUrl();
  /**
   * <code>string pfp_url = 2;</code>
   * @return The bytes for pfpUrl.
   */
  com.google.protobuf.ByteString
      getPfpUrlBytes();
}
