// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bankng.proto

package bankng;

public interface CreateTransactionRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bankng.CreateTransactionRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string from_iban = 1;</code>
   * @return The fromIban.
   */
  java.lang.String getFromIban();
  /**
   * <code>string from_iban = 1;</code>
   * @return The bytes for fromIban.
   */
  com.google.protobuf.ByteString
      getFromIbanBytes();

  /**
   * <code>string iban = 2;</code>
   * @return Whether the iban field is set.
   */
  boolean hasIban();
  /**
   * <code>string iban = 2;</code>
   * @return The iban.
   */
  java.lang.String getIban();
  /**
   * <code>string iban = 2;</code>
   * @return The bytes for iban.
   */
  com.google.protobuf.ByteString
      getIbanBytes();

  /**
   * <code>string name = 3;</code>
   * @return Whether the name field is set.
   */
  boolean hasName();
  /**
   * <code>string name = 3;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 3;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string amount = 4;</code>
   * @return The amount.
   */
  java.lang.String getAmount();
  /**
   * <code>string amount = 4;</code>
   * @return The bytes for amount.
   */
  com.google.protobuf.ByteString
      getAmountBytes();

  /**
   * <code>string transaction_id = 5;</code>
   * @return The transactionId.
   */
  java.lang.String getTransactionId();
  /**
   * <code>string transaction_id = 5;</code>
   * @return The bytes for transactionId.
   */
  com.google.protobuf.ByteString
      getTransactionIdBytes();

  bankng.CreateTransactionRequest.ToCase getToCase();
}
