// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bankng.proto

package bankng;

public interface CreateTransactionReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bankng.CreateTransactionReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.bankng.Transaction transaction = 1;</code>
   * @return Whether the transaction field is set.
   */
  boolean hasTransaction();
  /**
   * <code>.bankng.Transaction transaction = 1;</code>
   * @return The transaction.
   */
  bankng.Transaction getTransaction();
  /**
   * <code>.bankng.Transaction transaction = 1;</code>
   */
  bankng.TransactionOrBuilder getTransactionOrBuilder();
}
