// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: auth.proto

package bankng;

public interface FirstFactorReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bankng.FirstFactorReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string full_name = 1;</code>
   * @return The fullName.
   */
  java.lang.String getFullName();
  /**
   * <code>string full_name = 1;</code>
   * @return The bytes for fullName.
   */
  com.google.protobuf.ByteString
      getFullNameBytes();

  /**
   * <code>string first_name = 2;</code>
   * @return The firstName.
   */
  java.lang.String getFirstName();
  /**
   * <code>string first_name = 2;</code>
   * @return The bytes for firstName.
   */
  com.google.protobuf.ByteString
      getFirstNameBytes();

  /**
   * <code>string pfp_url = 3;</code>
   * @return The pfpUrl.
   */
  java.lang.String getPfpUrl();
  /**
   * <code>string pfp_url = 3;</code>
   * @return The bytes for pfpUrl.
   */
  com.google.protobuf.ByteString
      getPfpUrlBytes();

  /**
   * <code>string session_id = 4;</code>
   * @return The sessionId.
   */
  java.lang.String getSessionId();
  /**
   * <code>string session_id = 4;</code>
   * @return The bytes for sessionId.
   */
  com.google.protobuf.ByteString
      getSessionIdBytes();
}
