// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: accounts.proto

package bankng;

public interface ListAccountsReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bankng.ListAccountsReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .bankng.Account accounts = 1;</code>
   */
  java.util.List<bankng.Account> 
      getAccountsList();
  /**
   * <code>repeated .bankng.Account accounts = 1;</code>
   */
  bankng.Account getAccounts(int index);
  /**
   * <code>repeated .bankng.Account accounts = 1;</code>
   */
  int getAccountsCount();
  /**
   * <code>repeated .bankng.Account accounts = 1;</code>
   */
  java.util.List<? extends bankng.AccountOrBuilder> 
      getAccountsOrBuilderList();
  /**
   * <code>repeated .bankng.Account accounts = 1;</code>
   */
  bankng.AccountOrBuilder getAccountsOrBuilder(
      int index);
}
