// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bankng.proto

package bankng;

public interface ListAccountsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bankng.ListAccountsRequest)
    com.google.protobuf.MessageOrBuilder {
}
