// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: accounts.proto

package bankng;

public interface ListTransactionsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bankng.ListTransactionsRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string iban = 1;</code>
   * @return The iban.
   */
  java.lang.String getIban();
  /**
   * <code>string iban = 1;</code>
   * @return The bytes for iban.
   */
  com.google.protobuf.ByteString
      getIbanBytes();
}
