// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bankng.proto

package bankng;

public interface TransactionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bankng.Transaction)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.bankng.Correspondent correspondent = 1;</code>
   * @return Whether the correspondent field is set.
   */
  boolean hasCorrespondent();
  /**
   * <code>.bankng.Correspondent correspondent = 1;</code>
   * @return The correspondent.
   */
  bankng.Correspondent getCorrespondent();
  /**
   * <code>.bankng.Correspondent correspondent = 1;</code>
   */
  bankng.CorrespondentOrBuilder getCorrespondentOrBuilder();

  /**
   * <code>string amount = 2;</code>
   * @return The amount.
   */
  java.lang.String getAmount();
  /**
   * <code>string amount = 2;</code>
   * @return The bytes for amount.
   */
  com.google.protobuf.ByteString
      getAmountBytes();

  /**
   * <code>.google.protobuf.Timestamp timestamp = 5;</code>
   * @return Whether the timestamp field is set.
   */
  boolean hasTimestamp();
  /**
   * <code>.google.protobuf.Timestamp timestamp = 5;</code>
   * @return The timestamp.
   */
  com.google.protobuf.Timestamp getTimestamp();
  /**
   * <code>.google.protobuf.Timestamp timestamp = 5;</code>
   */
  com.google.protobuf.TimestampOrBuilder getTimestampOrBuilder();
}
