// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mucklet.proto

package bankng.mucklet;

public interface LookupCharacterRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bankng.mucklet.LookupCharacterRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string full_name = 1;</code>
   * @return The fullName.
   */
  java.lang.String getFullName();
  /**
   * <code>string full_name = 1;</code>
   * @return The bytes for fullName.
   */
  com.google.protobuf.ByteString
      getFullNameBytes();
}
