// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mucklet.proto

package bankng.mucklet;

public interface LookupCharacterRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bankng.mucklet.LookupCharacterRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string full_name = 1;</code>
   * @return Whether the fullName field is set.
   */
  boolean hasFullName();
  /**
   * <code>string full_name = 1;</code>
   * @return The fullName.
   */
  java.lang.String getFullName();
  /**
   * <code>string full_name = 1;</code>
   * @return The bytes for fullName.
   */
  com.google.protobuf.ByteString
      getFullNameBytes();

  /**
   * <code>string char_id = 2;</code>
   * @return Whether the charId field is set.
   */
  boolean hasCharId();
  /**
   * <code>string char_id = 2;</code>
   * @return The charId.
   */
  java.lang.String getCharId();
  /**
   * <code>string char_id = 2;</code>
   * @return The bytes for charId.
   */
  com.google.protobuf.ByteString
      getCharIdBytes();

  bankng.mucklet.LookupCharacterRequest.ByCase getByCase();
}
