// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mucklet.proto

package bankng.mucklet;

public interface LookupCharacterReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bankng.mucklet.LookupCharacterReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string first_name = 1;</code>
   * @return The firstName.
   */
  java.lang.String getFirstName();
  /**
   * <code>string first_name = 1;</code>
   * @return The bytes for firstName.
   */
  com.google.protobuf.ByteString
      getFirstNameBytes();

  /**
   * <code>string last_name = 2;</code>
   * @return The lastName.
   */
  java.lang.String getLastName();
  /**
   * <code>string last_name = 2;</code>
   * @return The bytes for lastName.
   */
  com.google.protobuf.ByteString
      getLastNameBytes();

  /**
   * <code>string pfp_url = 3;</code>
   * @return The pfpUrl.
   */
  java.lang.String getPfpUrl();
  /**
   * <code>string pfp_url = 3;</code>
   * @return The bytes for pfpUrl.
   */
  com.google.protobuf.ByteString
      getPfpUrlBytes();

  /**
   * <code>string char_id = 4;</code>
   * @return The charId.
   */
  java.lang.String getCharId();
  /**
   * <code>string char_id = 4;</code>
   * @return The bytes for charId.
   */
  com.google.protobuf.ByteString
      getCharIdBytes();
}
