// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mucklet.proto

package bankng.mucklet;

public final class MuckletOuterClass {
  private MuckletOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bankng_mucklet_SendMessageRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bankng_mucklet_SendMessageRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bankng_mucklet_LookupCharacterRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bankng_mucklet_LookupCharacterRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bankng_mucklet_LookupCharacterReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bankng_mucklet_LookupCharacterReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rmucklet.proto\022\016bankng.mucklet\032\033google/" +
      "protobuf/empty.proto\"6\n\022SendMessageReque" +
      "st\022\017\n\007char_id\030\001 \001(\t\022\017\n\007message\030\002 \001(\t\"F\n\026" +
      "LookupCharacterRequest\022\023\n\tfull_name\030\001 \001(" +
      "\tH\000\022\021\n\007char_id\030\002 \001(\tH\000B\004\n\002by\"_\n\024LookupCh" +
      "aracterReply\022\022\n\nfirst_name\030\001 \001(\t\022\021\n\tlast" +
      "_name\030\002 \001(\t\022\017\n\007pfp_url\030\003 \001(\t\022\017\n\007char_id\030" +
      "\004 \001(\t2\271\001\n\007Mucklet\022a\n\017LookupCharacter\022&.b" +
      "ankng.mucklet.LookupCharacterRequest\032$.b" +
      "ankng.mucklet.LookupCharacterReply\"\000\022K\n\013" +
      "SendMessage\022\".bankng.mucklet.SendMessage" +
      "Request\032\026.google.protobuf.Empty\"\000B\002P\001b\006p" +
      "roto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.EmptyProto.getDescriptor(),
        });
    internal_static_bankng_mucklet_SendMessageRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_bankng_mucklet_SendMessageRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bankng_mucklet_SendMessageRequest_descriptor,
        new java.lang.String[] { "CharId", "Message", });
    internal_static_bankng_mucklet_LookupCharacterRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_bankng_mucklet_LookupCharacterRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bankng_mucklet_LookupCharacterRequest_descriptor,
        new java.lang.String[] { "FullName", "CharId", "By", });
    internal_static_bankng_mucklet_LookupCharacterReply_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_bankng_mucklet_LookupCharacterReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bankng_mucklet_LookupCharacterReply_descriptor,
        new java.lang.String[] { "FirstName", "LastName", "PfpUrl", "CharId", });
    com.google.protobuf.EmptyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
