// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mucklet.proto

package bankng.mucklet;

public interface SendMessageRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bankng.mucklet.SendMessageRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string char_id = 1;</code>
   * @return The charId.
   */
  java.lang.String getCharId();
  /**
   * <code>string char_id = 1;</code>
   * @return The bytes for charId.
   */
  com.google.protobuf.ByteString
      getCharIdBytes();

  /**
   * <code>string message = 2;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
